apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc1-traffic-gen
  namespace: traffic-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dc1-traffic-gen
  template:
    metadata:
      labels:
        name: dc1-traffic-gen
    spec:
      containers:
      - name: dc1-traffic-gen
        image: phuongbac/traffic-generator1
        ports:
        - containerPort: 8089
        env:
        - name: CLUSTER_NAME
          value: "data-center1"
        - name: NAME_SPACE
          value: "sock-shop"
        - name: TARGET_HOST
          value: http://192.168.24.219:30001/
        - name: SVC_PORT
          value: "30001"
---
apiVersion: v1
kind: Service
metadata:
  name: dc1-traffic-gen
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: dc1-traffic-gen
  namespace: traffic-gen
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8089
    nodePort: 30001
  selector:
    name: dc1-traffic-gen